name = "mfz1mc"
author = "nitpum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "064a2da14baf0cbea4b05f17f912c317d215992b79d6f6b40cf829878640b296"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
