name = "mfz1mc"
author = "nitpum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30b170036dc556fb559706c9205d8a449f8bfa4892925f1c99aaaae0d6a52124"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
