name = "mfz1mc"
author = "nitpum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f86dc04983cafaf4262f1303e3a7f1f32398d7d16cde7425b8c2b309a2f8d54f"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
